apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: store-peer0
  namespace: store-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: store-peer0
  chart:
    git: git@github.com:ypevg/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: store-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
      pvc:
      deployment:
        
    peer:
      name: peer0
      gossippeeraddress: peer0.org3ambassador.gcptest.b2bchain.tech
      gossipexternalendpoint: peer0.store-net.org3ambassador.gcptest.b2bchain.tech:8443
      localmspid: storeMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.0
      couchdb:
        username: store-user

    storage:
      peer:
        storageclassname: storesc
        storagesize: 512Mi
      couchdb:
        storageclassname: storesc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: https://vault.test.b2bchain.tech
      authpath: devstore-net-auth
      secretprefix: secret/crypto/peerOrganizations/store-net/peers/peer0.store-net
      secretambassador: secret/crypto/peerOrganizations/store-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secret/credentials/store-net/couchdb/store?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "haproxy"
      external_url_suffix: org3ambassador.gcptest.b2bchain.tech
