apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-net-ca
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-net-ca
  chart:
    git: git@github.com:ypevg/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    deployment:
      annotations:
    annotations:  
      service:
      pvc:
    metadata:
      namespace: supplychain-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
    server:
      name: ca
      tlsstatus: true
      admin: supplychain-admin
    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi 
    vault:
      role: vault-role
      address: https://vault.test.b2bchain.tech
      authpath: devsupplychain-net-auth
      secretcert: secret/crypto/ordererOrganizations/supplychain-net/ca?ca.supplychain-net-cert.pem
      secretkey: secret/crypto/ordererOrganizations/supplychain-net/ca?supplychain-net-CA.key
      secretadminpass: secret/credentials/supplychain-net/ca/supplychain?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: orderer
      external_url_suffix: org1ambassador.gcptest.b2bchain.tech
